DDCNL-4316 | mongo upgrade
hmrc/pertax-frontend pull request #537
Opened 2021-10-22 15:02 UTC by Luka-Abey

- [x] compiles
- [x] unit tests pass
- [x] integration tests pass
- [x] ATs pass

2021-11-01 11:13 UTC, Sachin300793 commented on it/repositories/CachingItSpec.scala
>            val timeOffSet = 10L
val timeOffSet = 10L is unused , we can remove it.

2021-11-01 11:14 UTC, Sachin300793 commented on it/repositories/CachingItSpec.scala
> +  lazy val config = mock[ConfigDecorator]
We can remove mocking of ttl if it is unused

2021-11-01 11:15 UTC, Sachin300793 commented on it/repositories/CachingItSpec.scala
>            val timeOffSet = 10L
val timeOffSet = 10L is unused , we can remove it.

2021-11-01 11:49 UTC, Sachin300793 commented on it/repositories/CachingItSpec.scala
> +  lazy val config = mock[ConfigDecorator]
removed

2021-11-01 11:49 UTC, Sachin300793 commented on it/repositories/CachingItSpec.scala
>            val timeOffSet = 10L
removed

2021-11-01 15:43 UTC, pascal22p requested changes

2021-11-01 15:43 UTC, pascal22p commented on app/repositories/EditAddressLockRepository.scala
> +      .map(_.toList)
The filter on expire_at is missing

2021-11-02 11:57 UTC, Sachin300793 commented on it/repositories/CachingItSpec.scala
> +          Thread.sleep(55000)
removed and updated tests

2021-11-02 11:58 UTC, Sachin300793 commented on app/repositories/EditAddressLockRepository.scala
> +      .map(_.toList)
Added filter for expire_at

2021-11-02 17:00 UTC, pascal22p approved these changes

2021-11-18 16:03 UTC, merged