DDCNL-5278: RLS Removal
hmrc/pertax-frontend pull request #551
Opened 2022-01-31 16:56 UTC by Christian-QA

2022-02-09 15:02 UTC, pascal22p requested changes

2022-02-09 15:02 UTC, pascal22p commented on conf/messages
> +label.check_your_address_action=to make sure you get essential tax letters.
welsh?

2022-02-09 15:06 UTC, Christian-QA commented on conf/messages
> +label.check_your_address_action=to make sure you get essential tax letters.
https://docs.google.com/spreadsheets/d/1qzYXeXAGmQ8QRXLvYkNCVg7RS99q0MGKd4RreHCy__0/edit#gid=0 Still waiting

2022-02-09 15:37 UTC, pascal22p commented on app/models/Address.scala
> +  status: Option[Int]
the user don't get interrupted and continue its journey. The exception is for us to chase after those not agreed value.

2022-02-21 11:59 UTC, pascal22p approved these changes

2022-02-21 13:00 UTC, Luka-Abey approved these changes

2022-02-24 12:18 UTC, merged