DDCNL-5818: Removed UTR from SA Request Access Page
hmrc/pertax-frontend pull request #588
Opened 2022-04-25 14:38 UTC by Christian-QA

2022-04-25 14:55 UTC, Luka-Abey approved these changes

2022-04-26 08:44 UTC, pascal22p requested changes

2022-04-26 08:44 UTC, pascal22p commented on app/controllers/SelfAssessmentController.scala
> +          Ok(requestAccessToSelfAssessmentView(deadlineYear))
Jira ticket says for CL50 users. Here it is for all users.

2022-04-26 12:22 UTC, pascal22p approved these changes

2022-04-26 12:22 UTC, pascal22p commented on app/controllers/SelfAssessmentController.scala
> +          Ok(requestAccessToSelfAssessmentView(deadlineYear))
James is happy with this so approving

2022-04-29 12:26 UTC, merged