BTA account menu link check added
hmrc/pertax-frontend pull request #620
Opened 2022-07-15 13:00 UTC by Nj147

2022-07-15 13:33 UTC, Christian-QA submitted a review, later dismissed

2022-07-18 09:38 UTC, pascal22p requested changes

2022-07-18 09:38 UTC, pascal22p commented on app/views/MainView.scala.html
> +                                case saWithActionNeeded =>
Default case is missing

2022-07-18 10:08 UTC, pascal22p approved these changes

2022-07-18 14:16 UTC, merged