DDCNL-6204: Incremented hmrc mongo versiong
hmrc/pertax-frontend pull request #624
Opened 2022-07-25 14:51 UTC by Christian-QA

2022-07-25 15:47 UTC, SandeepUmredkar approved these changes

2022-07-26 14:04 UTC, Luka-Abey approved these changes

2022-07-26 14:11 UTC, Nj147 requested changes

2022-07-26 14:11 UTC, Nj147 commented on project/AppDependencies.scala
> +    "uk.gov.hmrc.mongo"   %% s"hmrc-mongo-$playVersion" % "0.67.0",
Can you just have the test dependency as 0.67.0? The bobby rule will trigger for anything below 0.68.0 so this will still fail won't it?

2022-07-26 14:50 UTC, Nj147 approved these changes

2022-07-26 15:57 UTC, merged