DDCNL-6649
hmrc/pertax-frontend pull request #673
Opened 2022-12-23 09:37 UTC by SandeepUmredkar

2023-01-05 10:01 UTC, pascal22p commented on app/config/ConfigDecorator.scala
> +
We should link to the welsh version of those urls if they exist if welsh is used on our side.

2023-01-05 10:04 UTC, pascal22p commented on app/controllers/InterstitialController.scala
> +    if (childBenefitSingleAccountToggleValue.isEmpty || !childBenefitSingleAccountToggleValue.get.get.isEnabled) {
`.get.get` ?? Use a map:

`
    featureFlagService.get(ChildBenefitSingleAccountToggle).map { featureFlag =>
      if (featureFlag.isEnabled) {
        ???
      } else ???
   }
`

2023-01-05 10:05 UTC, pascal22p commented on app/controllers/InterstitialController.scala
> +    if (childBenefitSingleAccountToggleValue.nonEmpty && childBenefitSingleAccountToggleValue.get.get.isEnabled) {
Same as above

2023-01-05 10:08 UTC, pascal22p commented on app/controllers/controllershelpers/HomeCardGenerator.scala
> +    if (childBenefitSingleAccountToggleValue.nonEmpty && childBenefitSingleAccountToggleValue.get.get.isEnabled) {
Again, use map

2023-01-05 10:33 UTC, pascal22p requested changes
see comments

2023-01-12 10:48 UTC, pascal22p requested changes

2023-01-12 10:48 UTC, pascal22p commented on app/controllers/InterstitialController.scala
> +        errorRenderer.error(UNAUTHORIZED)
Can you redirect to the new page using a 301 status.
Remember that urls get bookmarked or can be used by other services. Always send the user to the new location is the url changes.

2023-01-12 10:50 UTC, pascal22p commented on app/config/ConfigDecorator.scala
> +
This has been taken to gov.uk for the welsh urls

2023-01-19 09:41 UTC, pascal22p approved these changes

2023-01-19 09:44 UTC, pascal22p requested changes

2023-01-19 09:44 UTC, pascal22p commented on app/config/ConfigDecorator.scala
> +
We need the welsh

2023-01-19 09:44 UTC, pascal22p commented on app/config/ConfigDecorator.scala
> +
We need the welsh

2023-01-19 09:44 UTC, pascal22p commented on app/config/ConfigDecorator.scala
> +
We need the welsh

2023-01-19 10:23 UTC, pascal22p submitted a review, later dismissed

2023-02-16 11:00 UTC, askar-makkunnath approved these changes

2023-02-20 15:42 UTC, merged