[DDCNL-6919] Removed tax-credits-payment-link
hmrc/pertax-frontend pull request #683
Opened 2023-02-08 11:38 UTC by vfryer12

2023-02-10 16:09 UTC, pascal22p requested changes

2023-02-10 16:09 UTC, pascal22p commented on app/views/cards/home/TaxCreditsView.scala.html
> -    @if(showTaxCreditsPaymentLink) {
The parameter `showTaxCreditsPaymentLink` line 19 above need also deleting

2023-02-22 15:21 UTC, Christian-QA approved these changes

2023-02-23 17:14 UTC, pascal22p submitted a review, later dismissed

2023-03-01 15:08 UTC, merged