Ddcnl 7975
hmrc/pertax-frontend pull request #788
Opened 2024-01-19 07:45 UTC by grantrobson

2024-02-20 10:04 UTC, SandeepUmredkar requested changes

2024-02-20 10:11 UTC, grantrobson commented on app/connectors/EnhancedPartialRetriever.scala
> +    def requestBuilder: RequestBuilder = {
Good point. I've moved it to private method

2024-02-20 10:12 UTC, grantrobson commented on app/connectors/EnhancedPartialRetriever.scala
> +      case _                 => Nil
It is like this in main so I feel it's best to leave as is

2024-02-21 09:46 UTC, SandeepUmredkar submitted a review, later dismissed

2024-03-05 10:07 UTC, SandeepUmredkar approved these changes

2024-03-05 11:04 UTC, merged