DDCNL-8690
hmrc/pertax-frontend pull request #802
Opened 2024-04-02 09:35 UTC by SandeepUmredkar

2024-04-02 15:25 UTC, pascal22p requested changes

2024-04-02 15:25 UTC, pascal22p commented on conf/application.conf
> +    enabled = true
Default should be false so that no override is needed in production

2024-04-03 13:39 UTC, Nj147 approved these changes

2024-04-03 15:44 UTC, pascal22p approved these changes

2024-04-04 10:41 UTC, merged