DDCNL-9621
hmrc/pertax-frontend pull request #854
Opened 2024-11-15 09:29 UTC by SandeepUmredkar

2024-11-18 11:00 UTC, pascal22p requested changes

2024-11-19 12:08 UTC, SandeepUmredkar commented on conf/application.conf
> +    change-bank-account-location = "/child-benefit/change-bank/change-account"
I have added the whole URL in the conf. Is this what you are suggesting?

2024-11-27 09:50 UTC, grantrobson approved these changes

2024-11-28 10:02 UTC, pascal22p approved these changes

2024-11-28 15:46 UTC, merged